### ISSUE TITLE
Can you share the training/testing split, segmentation maps and image ID of the SVA dataset?

### ISSUE THREAD

**Issue by Ha0Tang** [kregmi/cross-view-image-synthesis#28]
Can you share the training/testing split and segmentation maps of the SVA dataset?
And can you share the image ID of Fig 7 in your extension paper for comparison?
Thank you in advance!

**Comment by kregmi** [comment]
We used the same training/test split as provided in the original dataset. Since the consecutive frames are very similar, we used every tenth frame to remove redundancy in the dataset. 

The IDs  for images in Figure 7 are in the format: set#_img#. Following images are shown as qualitative results.
 033_004170.jpg, 011_001290.jpg, 014_001130.jpg, 019_002970.jpg.

**Comment by kregmi** [comment]
For segmentation maps, we used the same RefineNet architecture as in the CVPR paper. Just know that you can use any pre-trained model to obtain the segmentation maps. Please give me few days if you want me to share the segmentation maps with you.

**Comment by Ha0Tang** [comment]
Ok, many thanks.

**Comment by Ha0Tang** [comment]
Hi @Kermi,
In your paper, you said there are 100 subsets in training set, however, the dataset contains 200 training sets. Can you give more details about this? Thank you very much.

**Comment by kregmi** [comment]
I couldn't locate the training dataset (and the segmentation maps) because I have issues with my machine. I know that I randomly picked the 100 sets for training. You can use any of the 100 sets or use all 200 sets for your training. It should not matter since it is for training purpose. Only reason I used 100 sets is because for me, 200 sets would be too many images and would take a lot of time for training.

**Comment by Kermi** [comment]
Sorry. I think you are sending your emails to the wrong person. I have no
idea how they relate to me.

Kind regards
